name = "batterylink"
main = "worker/index.js"
compatibility_date = "2025-07-12"
account_id = "9df138cc6e3f2aee3531fd5aaa9e7b61"

[assets]
not_found_handling = "single-page-application"

[observability]
enabled = true
